import type { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",
  ORGANIZATION_MEMBERS_READ: "organization:members:read",
  ORGANIZATION_MEMBERS_MANAGE: "organization:members:manage",

  KNOWLEDGE_READ: "knowledge:read",
  KNOWLEDGE_UPLOAD: "knowledge:upload",
  KNOWLEDGE_INGEST: "knowledge:ingest",
  KNOWLEDGE_DELETE: "knowledge:delete",

  CHAT_ASK: "chat:ask",
  CHAT_READ: "chat:read",
  CHAT_DELETE: "chat:delete",
  AGENT_TOOL_APPROVE: "agent_tool:approve",
  USAGE_READ: "usage:read",
  AUDIT_LOG_READ: "audit_log:read",

  ADMIN_ACCESS: "admin:access",

  AGENT_RUN_READ: "agent_run:read",
  AGENT_RUN_DEBUG: "agent_run:debug",

  INTEGRATION_READ: "integration:read",
  INTEGRATION_MANAGE: "integration:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  OWNER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_MANAGE,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,
    PERMISSIONS.KNOWLEDGE_DELETE,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,
    PERMISSIONS.CHAT_DELETE,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ,

    PERMISSIONS.ADMIN_ACCESS,

    PERMISSIONS.AGENT_TOOL_APPROVE,

    PERMISSIONS.AGENT_RUN_READ,
    PERMISSIONS.AGENT_RUN_DEBUG,

    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.INTEGRATION_MANAGE
  ],

  ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,
    PERMISSIONS.KNOWLEDGE_DELETE,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,
    PERMISSIONS.CHAT_DELETE,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ,

    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.AGENT_TOOL_APPROVE,

    PERMISSIONS.AGENT_RUN_READ,
    PERMISSIONS.AGENT_RUN_DEBUG,

    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.INTEGRATION_MANAGE
  ],

  DEVELOPER: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,
    PERMISSIONS.CHAT_DELETE,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ,
    PERMISSIONS.AGENT_TOOL_APPROVE,

    PERMISSIONS.AGENT_RUN_READ,
    PERMISSIONS.AGENT_RUN_DEBUG,

    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.INTEGRATION_MANAGE
  ],

  SUPPORT_AGENT: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.KNOWLEDGE_READ,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,
    PERMISSIONS.CHAT_DELETE,

    PERMISSIONS.AGENT_RUN_READ,
    PERMISSIONS.INTEGRATION_READ,
  ],

  VIEWER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.CHAT_READ,

    PERMISSIONS.AGENT_RUN_READ,
  ],
};

export function roleHasPermission(role: UserRole, permission: Permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
