import type { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",
  ORGANIZATION_MEMBERS_READ: "organization:members:read",
  ORGANIZATION_MEMBERS_MANAGE: "organization:members:manage",

  KNOWLEDGE_READ: "knowledge:read",
  KNOWLEDGE_UPLOAD: "knowledge:upload",
  KNOWLEDGE_INGEST: "knowledge:ingest",
  KNOWLEDGE_DELETE: "knowledge:delete",

  CHAT_ASK: "chat:ask",
  CHAT_READ: "chat:read",

  USAGE_READ: "usage:read",
  AUDIT_LOG_READ: "audit_log:read",

  ADMIN_ACCESS: "admin:access"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  OWNER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,
    PERMISSIONS.ORGANIZATION_MEMBERS_MANAGE,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,
    PERMISSIONS.KNOWLEDGE_DELETE,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ,

    PERMISSIONS.ADMIN_ACCESS
  ],

  ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_READ,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,
    PERMISSIONS.KNOWLEDGE_DELETE,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ,

    PERMISSIONS.ADMIN_ACCESS
  ],

  DEVELOPER: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_INGEST,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ,

    PERMISSIONS.USAGE_READ,
    PERMISSIONS.AUDIT_LOG_READ
  ],

  SUPPORT_AGENT: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.KNOWLEDGE_READ,

    PERMISSIONS.CHAT_ASK,
    PERMISSIONS.CHAT_READ
  ],

  VIEWER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.CHAT_READ
  ]
};

export function roleHasPermission(role: UserRole, permission: Permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}